# -*- coding: utf-8 -*-
"""SPPRnano.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10d8RSLYNW_1dOjnrvWF7_pUTEveYTY_4
"""

import streamlit as st
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
import re
import statsmodels.api as sm

# ======================
# КОНФИГУРАЦИЯ
# ======================
st.set_page_config(page_title="DoseRanker Pro", layout="wide", initial_sidebar_state="expanded")

st.title("🎯 DoseRanker Pro")
st.markdown("**Полная математическая модель многокритериальной оптимизации доз**")

# ======================
# ПРАВИЛА ЭКСПЕРИМЕНТОВ
# ======================
EXPERIMENT_RULES = {
    "Rats_ZnO": {
        "name": "Крысы Wistar (ZnO НЧ)",
        "efficiency_keywords": ["Zn", "SOD", "CA4", "ALP_liver", "Li_liver", "I_liver", "weight", "масса"],
        "toxic_keywords": ["As", "Pb", "Hg", "Cr", "ALP_blood", "ZAG_brain"],
        "balance_ratios": ["Na/K", "Ca/Mg", "Ca/P", "Zn/Cu"]
    },
    "Carp_Metals": {
        "name": "Карпы (Mg/Mn/Cu-C)",
        "efficiency_keywords": ["weight", "масса", "белок", "RBC", "HGB", "HCT"],
        "toxic_keywords": ["Pb", "Cd", "глюкоза", "холестерин"],
        "balance_ratios": ["Ca/Fe", "V/Pb"]
    }
}

# ======================
# РОБАСТНАЯ ПРЕДОБРАБОТКА
# ======================
def safe_numeric(col, lod=0.00005):
    """Обработка <LOD, запятых и текстовых значений"""
    s = col.astype(str).str.strip()

    # Обработка <число
    def extract_censored(val):
        match = re.search(r'<([0-9,\\.]+)', str(val))
        if match:
            return lod
        return val

    s = s.apply(extract_censored)
    s = s.str.replace(',', '.', regex=False).str.replace(' ', '', regex=False)
    s = s.replace(['', 'nan', 'NaN', 'None'], np.nan)

    return pd.to_numeric(s, errors='coerce')

def winsorize_feature(series, limits=(0.05, 0.95)):
    """Winsorizing выбросов"""
    data = series.dropna()
    if len(data) > 3:
        lower, upper = data.quantile([limits[0], limits[1]])
        return series.clip(lower=lower, upper=upper)
    return series

def visualize_outliers(df, features):
    """Визуализация выбросов"""
    st.subheader("🔍 Анализ выбросов")
    n_cols = min(3, len(features))

    for i in range(0, len(features), n_cols):
        cols = st.columns(n_cols)
        for j, feature in enumerate(features[i:i+n_cols]):
            if j < len(cols):
                with cols[j]:
                    fig, ax = plt.subplots(figsize=(5, 3))
                    data = df[feature].dropna()
                    if len(data) > 3:
                        sns.boxplot(y=data, ax=ax)
                        ax.set_title(f"{feature}\nn={len(data)}")
                    plt.tight_layout()
                    st.pyplot(fig)
                    plt.close(fig)

# ======================
# 4.2.1 ПРОВЕРКА ДОЗОЗАВИСИМОСТИ
# ======================
def compute_dose_sensitivity(df, dose_col, features, alpha=0.05):
    """Kruskal-Wallis + Spearman + квадратичная регрессия"""
    results = []

    def kruskal_safe(x, groups):
        df_test = pd.DataFrame({'x': x, 'group': groups}).dropna()
        if len(df_test) < 6 or df_test['group'].nunique() < 2:
            return np.nan
        samples = [g['x'].dropna().values for _, g in df_test.groupby('group')]
        if any(len(s) < 2 for s in samples):
            return np.nan
        try:
            return stats.kruskal(*samples)[1]
        except:
            return np.nan

    for feature in features:
        x = df[feature]
        doses = df[dose_col]
        valid = ~x.isna() & ~doses.isna()

        if valid.sum() < 10:
            results.append({'marker': feature, 'p_kw': np.nan, 'rho': np.nan,
                          'p_spear': np.nan, 'p_quad': np.nan, 'dose_sensitive': False})
            continue

        # Kruskal-Wallis
        p_kw = kruskal_safe(x[valid].values, doses[valid].values)

        # Spearman
        if valid.sum() >= 4:
            rho, p_spear = stats.spearmanr(doses[valid], x[valid])
        else:
            rho, p_spear = np.nan, np.nan

        # Квадратичная регрессия
        p_quad = np.nan
        try:
            df_reg = pd.DataFrame({'dose': doses[valid].values, 'x': x[valid].values})
            if len(df_reg) > 5:
                X = sm.add_constant(pd.DataFrame({
                    'dose': df_reg['dose'],
                    'dose2': df_reg['dose']**2
                }))
                model = sm.OLS(df_reg['x'], X).fit()
                p_quad = model.pvalues.get('dose2', np.nan)
        except:
            pass

        # ✅ ИСПРАВЛЕНА логика (правильные скобки)
        is_sensitive = False
        if not pd.isna(p_kw) and p_kw < alpha:
            is_sensitive = True
        elif not pd.isna(p_quad) and p_quad < alpha:
            is_sensitive = True

        results.append({
            'marker': feature,
            'p_kw': p_kw,
            'rho': rho,
            'p_spear': p_spear,
            'p_quad': p_quad,
            'dose_sensitive': is_sensitive
        })

    return pd.DataFrame(results)

# ======================
# 4.3 КРИТЕРИЙ БАЛАНСА
# ======================
def compute_balance_criterion(df, dose_col, control_dose, balance_ratios, features):
    """Критерий баланса через физиологические отношения"""
    B_vals = {}
    doses = sorted(df[dose_col].dropna().unique())

    for dose in doses:
        deviations = []
        for ratio in balance_ratios:
            if '/' in ratio:
                num, den = ratio.split('/')
                num_cols = [col for col in features if num.lower() in col.lower()]
                den_cols = [col for col in features if den.lower() in col.lower()]

                if num_cols and den_cols:
                    num_col, den_col = num_cols[0], den_cols[0]
                    dose_data = df[df[dose_col] == dose][[num_col, den_col]].dropna()
                    ctrl_data = df[df[dose_col] == control_dose][[num_col, den_col]].dropna()

                    if len(dose_data) > 0 and len(ctrl_data) > 0:
                        dose_ratio = (dose_data[num_col] / dose_data[den_col]).median()
                        ctrl_ratio = (ctrl_data[num_col] / ctrl_data[den_col]).median()

                        all_data = df[[num_col, den_col]].dropna()
                        all_ratios = all_data[num_col] / all_data[den_col]
                        iqr_ratio = np.percentile(all_ratios.dropna(), 75) - np.percentile(all_ratios.dropna(), 25)

                        if iqr_ratio > 0:
                            deviation = abs((dose_ratio - ctrl_ratio) / iqr_ratio)
                            deviations.append(deviation)

        B_vals[dose] = -np.median(deviations) if deviations else 0.0
    return B_vals

# ======================
# ВСПОМОГАТЕЛЬНАЯ ФУНКЦИЯ ДЛЯ RERUN
# ======================
def safe_rerun():
    """Совместимость с разными версиями Streamlit"""
    try:
        st.rerun()
    except AttributeError:
        st.experimental_rerun()

# ======================
# ОСНОВНОЙ ИНТЕРФЕЙС
# ======================

st.sidebar.header("📁 Загрузка данных")
uploaded_file = st.sidebar.file_uploader("CSV/Excel", type=["csv", "xlsx"])

if uploaded_file is not None:
    try:
        # Чтение файла
        if uploaded_file.name.endswith('.csv'):
            df_raw = pd.read_csv(uploaded_file, sep=None, decimal=',', engine='python')
        else:
            df_raw = pd.read_excel(uploaded_file)

        st.session_state.df_raw = df_raw
        st.success(f"✅ Загружено: {len(df_raw)} строк, {len(df_raw.columns)} столбцов")
        st.write("Первые 5 строк:")
        st.dataframe(df_raw.head())

        # Выбор эксперимента
        st.sidebar.header("🧪 Эксперимент")
        exp_type = st.sidebar.selectbox("Тип эксперимента", list(EXPERIMENT_RULES.keys()))
        rules = EXPERIMENT_RULES[exp_type]

        # Обработка столбца доз
        st.sidebar.header("⚙️ Столбцы")
        dose_col = st.sidebar.selectbox("Столбец с дозами", df_raw.columns)

        # Безопасная обработка доз (запятые → точки)
        dose_raw = safe_numeric(df_raw[dose_col])
        if dose_raw.isna().all():
            st.error("❌ Не удалось преобразовать столбец доз в числа!")
            st.stop()

        # Сохраняем числовые дозы
        df_raw['dose_numeric'] = dose_raw
        dose_col_numeric = 'dose_numeric'

        unique_doses = sorted(dose_raw.dropna().unique())
        st.sidebar.markdown(f"**Найденные дозы:** {', '.join([f'{d:.2f}' for d in unique_doses])}")

        # ✅ Selectbox с форматированными метками
        dose_options = {f"{d:.2f}": d for d in unique_doses}
        control_dose_label = st.sidebar.selectbox(
            "🎯 Контрольная доза",
            options=list(dose_options.keys()),
            index=0
        )
        control_dose = dose_options[control_dose_label]

        # Числовые признаки
        all_numeric = df_raw.select_dtypes(include=[np.number]).columns.tolist()
        numeric_cols = [c for c in all_numeric if c != dose_col_numeric]

        features = st.sidebar.multiselect(
            "📊 Признаки для анализа",
            numeric_cols,
            default=numeric_cols[:min(15, len(numeric_cols))]
        )

        if st.sidebar.button("🚀 Запустить анализ", type="primary") and features:
            # Полная предобработка
            df_processed = df_raw.copy()
            df_processed[dose_col_numeric] = dose_raw

            for col in features:
                df_processed[col] = safe_numeric(df_raw[col])

            st.session_state.df_processed = df_processed
            st.session_state.features = features
            st.session_state.dose_col = dose_col_numeric
            st.session_state.control_dose = float(control_dose)
            st.session_state.rules = rules
            st.session_state.unique_doses = unique_doses

            # Очистка предыдущих результатов
            for key in ['df_clean', 'dose_stats', 'results']:
                if key in st.session_state:
                    del st.session_state[key]

            st.success("✅ Данные готовы к анализу!")
            safe_rerun()

    except Exception as e:
        st.error(f"❌ Ошибка загрузки: {str(e)}")
        import traceback
        st.code(traceback.format_exc())
        st.stop()

# ======================
# ГЛАВНЫЙ АНАЛИЗ
# ======================
if 'df_processed' in st.session_state:
    df = st.session_state.df_processed
    features = st.session_state.features
    dose_col = st.session_state.dose_col
    control_dose = st.session_state.control_dose
    rules = st.session_state.rules

    st.markdown("---")

    # Шаг 1: Выбросы
    st.header("🔍 **Шаг 1: Анализ выбросов**")
    col1, col2 = st.columns([3, 1])

    with col1:
        if st.button("📈 Показать выбросы"):
            visualize_outliers(df, features)

    with col2:
        outlier_method = st.radio("Обработка выбросов", ["none", "winsorize"])

    if st.button("⚙️ Применить обработку выбросов"):
        df_clean = df.copy()
        if outlier_method == "winsorize":
            for feature in features:
                df_clean[feature] = winsorize_feature(df_clean[feature])
        st.session_state.df_clean = df_clean
        st.success("✅ Обработка выбросов применена!")
        safe_rerun()

    # Шаг 2: Дозозависимость 4.2.1
    if 'df_clean' in st.session_state:
        df_final = st.session_state.df_clean

        st.markdown("---")
        st.header("🔬 **Шаг 2: Дозозависимость маркеров**")

        if st.button("📊 Анализ дозочувствительности", key="dose_analysis"):
            with st.spinner("Kruskal-Wallis + квадратичная регрессия..."):
                dose_stats = compute_dose_sensitivity(df_final, dose_col, features)
                st.session_state.dose_stats = dose_stats

        # Показываем результаты, если они есть
        if 'dose_stats' in st.session_state:
            dose_stats = st.session_state.dose_stats
            sensitive = dose_stats[dose_stats['dose_sensitive']]
            col1, col2 = st.columns(2)

            with col1:
                st.markdown("**✅ ДОЗОЧУВСТВИТЕЛЬНЫЕ**")
                if len(sensitive) > 0:
                    st.dataframe(sensitive[['marker', 'p_kw', 'p_quad', 'rho']]
                               .round(4).sort_values('p_kw'))
                else:
                    st.warning("Не найдено дозочувствительных маркеров")

            with col2:
                st.markdown("**📈 Все маркеры**")
                st.dataframe(dose_stats.round(4))

            st.metric("Дозочувствительных", f"{len(sensitive)}/{len(features)}")

        # Шаг 3: Многокритериальный анализ
    if 'dose_stats' in st.session_state:
        st.markdown("---")
        st.header("🎯 **Шаг 3: Многокритериальный анализ**")

        # 3.1 Исходный список дозозависимых маркеров
        sensitive_markers = st.session_state.dose_stats[
            st.session_state.dose_stats['dose_sensitive']
        ]['marker'].tolist()

        # Если нет дозочувствительных - используем все
        if not sensitive_markers:
            st.warning("⚠️ Нет дозочувствительных маркеров, используем все признаки")
            sensitive_markers = features

        # 3.2 Отбор с учётом корреляций (убираем сильно коррелирующие маркеры)
        df_final = st.session_state.df_clean

        # Берём только столбцы из sensitive_markers, которые реально есть в df_final
        corr_cols = [m for m in sensitive_markers if m in df_final.columns]

        if len(corr_cols) > 1:
            corr_matrix = df_final[corr_cols].corr(method='pearson')

            # Порог по модулю корреляции
            corr_threshold = 0.9

            to_drop = set()
            cols = corr_matrix.columns.tolist()

            for i in range(len(cols)):
                for j in range(i + 1, len(cols)):
                    if abs(corr_matrix.iloc[i, j]) > corr_threshold:
                        # Удаляем один из двух, например второй
                        to_drop.add(cols[j])

            reduced_markers = [c for c in corr_cols if c not in to_drop]

            if to_drop:
                st.info(
                    f"Удалено {len(to_drop)} сильно коррелирующих маркеров "
                    f"(порог |r| > {corr_threshold:.1f}). "
                    f"Осталось {len(reduced_markers)} маркеров."
                )
            else:
                st.info("Сильно коррелирующих маркеров не обнаружено.")

            sensitive_markers = reduced_markers
        else:
            st.info("Для анализа корреляций нужно хотя бы два маркера.")

        # Дальше – автоотбор M_E, M_S уже из обновлённого sensitive_markers
        me_auto = [m for m in sensitive_markers
                   if any(kw.lower() in str(m).lower() for kw in rules["efficiency_keywords"])]
        ms_auto = [m for m in sensitive_markers
                   if any(kw.lower() in str(m).lower() for kw in rules["toxic_keywords"])]

        col1, col2 = st.columns(2)
        with col1:
            st.markdown("**M_E Эффективность**")
            me_selected = st.multiselect(
                "Выберите",
                sensitive_markers,
                default=me_auto[:5] if me_auto else sensitive_markers[:3],
                key="me_select"
            )
        with col2:
            st.markdown("**M_S Безопасность**")
            ms_selected = st.multiselect(
                "Выберите",
                sensitive_markers,
                default=ms_auto[:5] if ms_auto else [],
                key="ms_select"
            )
    
        # ✅ СЛАЙДЕРЫ ВЫНЕСЕНЫ ЗА ПРЕДЕЛЫ КНОПКИ
        st.markdown("### ⚖️ Веса критериев")
        col1, col2, col3 = st.columns(3)
        w_E = col1.slider("w₁ Эффективность", 0.0, 1.0, 0.3, 0.05, key="w_e")
        w_B = col2.slider("w₂ Баланс", 0.0, 1.0, 0.3, 0.05, key="w_b")
        w_S = col3.slider("w₃ Безопасность", 0.0, 1.0, 0.4, 0.05, key="w_s")

        # Нормализация весов
        w_total = w_E + w_B + w_S
        if w_total > 0:
            w_E_norm, w_B_norm, w_S_norm = w_E/w_total, w_B/w_total, w_S/w_total
            st.caption(f"Нормализованные веса: E={w_E_norm:.2f}, B={w_B_norm:.2f}, S={w_S_norm:.2f}")

        # 🔥 ПОЛНЫЙ РАСЧЕТ 4.2-4.7
        if st.button("🚀 Рассчитать E_g, B_g, S_g → I_g", type="primary", key="calc_btn"):
            if not me_selected:
                st.error("❌ Выберите хотя бы один маркер эффективности!")
            else:
                df_final = st.session_state.df_clean
                doses = sorted(df_final[dose_col].dropna().unique())

                # 4.2 Эффективность
                E_vals = {}
                for dose in doses:
                    shifts = []
                    for m in me_selected:
                        group_data = df_final[df_final[dose_col] == dose][m].dropna()
                        ctrl_data = df_final[df_final[dose_col] == control_dose][m].dropna()
                        if len(group_data) > 0 and len(ctrl_data) > 0:
                            q75 = df_final[m].quantile(0.75)
                            q25 = df_final[m].quantile(0.25)
                            iqr_m = q75 - q25
                            if iqr_m > 0:
                                shift = (group_data.median() - ctrl_data.median()) / iqr_m
                                shifts.append(shift)
                    E_vals[dose] = np.nanmedian(shifts) if shifts else 0

                # 4.4 Безопасность
                S_vals = {}
                for dose in doses:
                    risks = []
                    for m in ms_selected:
                        group_data = df_final[df_final[dose_col] == dose][m].dropna()
                        ctrl_data = df_final[df_final[dose_col] == control_dose][m].dropna()
                        if len(group_data) > 0 and len(ctrl_data) > 0:
                            q75 = df_final[m].quantile(0.75)
                            q25 = df_final[m].quantile(0.25)
                            iqr_m = q75 - q25
                            if iqr_m > 0:
                                risk = max(0, (group_data.median() - ctrl_data.median()) / iqr_m)
                                risks.append(risk)
                    S_vals[dose] = np.nanmedian(risks) if risks else 0

                # 4.3 Баланс
                B_vals = compute_balance_criterion(df_final, dose_col, control_dose,
                                                 rules["balance_ratios"], features)

                # 4.5 Нормализация
                def normalize(d):
                    vals = [v for v in d.values() if not pd.isna(v)]
                    if not vals:
                        return {k: 0.5 for k in d}
                    vmin, vmax = min(vals), max(vals)
                    if vmax == vmin:
                        return {k: 0.5 for k in d}
                    return {k: (v-vmin)/(vmax-vmin) for k, v in d.items()}

                E_norm = normalize(E_vals)
                B_norm = normalize(B_vals)
                S_norm = normalize(S_vals)

                # 4.6 Интегральный индекс
                results = pd.DataFrame({
                    'Доза': list(E_vals.keys()),
                    'E_g': list(E_vals.values()),
                    'B_g': list(B_vals.values()),
                    'S_g': list(S_vals.values()),
                    'E_norm': list(E_norm.values()),
                    'B_norm': list(B_norm.values()),
                    'S_norm': list(S_norm.values()),
                })

                # Вычисляем I_g с нормализованными весами
                results['I_g'] = (w_E_norm * results['E_norm'] +
                                 w_B_norm * results['B_norm'] -
                                 w_S_norm * results['S_norm'])

                st.session_state.results = results

        # ✅ ПОКАЗЫВАЕМ РЕЗУЛЬТАТЫ ОТДЕЛЬНО (сохраняются при изменении слайдеров)
        if 'results' in st.session_state:
            results = st.session_state.results.copy()

            # Пересчитываем I_g с текущими весами
            results['I_g'] = (w_E_norm * results['E_norm'] +
                             w_B_norm * results['B_norm'] -
                             w_S_norm * results['S_norm'])

            # 🏆 РЕЗУЛЬТАТЫ
            st.markdown("### 🏆 **ОПТИМИЗАЦИЯ ДОЗ**")

            # Форматируем дозу для отображения
            results_display = results.copy()
            results_display['Доза'] = results_display['Доза'].apply(lambda x: f"{x:.2f}")

            st.dataframe(
                results_display.round(3).sort_values('I_g', ascending=False),
                use_container_width=True
            )

            # Графики
            fig, axes = plt.subplots(1, 3, figsize=(18, 5))
            doses_num = results['Доза'].tolist()
            x_pos = range(len(doses_num))
            x_labels = [f'{d:.1f}' for d in doses_num]

            axes[0].bar(x_pos, results['E_norm'], color='green', alpha=0.8)
            axes[0].set_title('E_g Эффективность', fontweight='bold')
            axes[0].set_xticks(x_pos)
            axes[0].set_xticklabels(x_labels, rotation=45)
            axes[0].set_xlabel('Доза')

            axes[1].bar(x_pos, results['B_norm'], color='blue', alpha=0.8)
            axes[1].set_title('B_g Баланс', fontweight='bold')
            axes[1].set_xticks(x_pos)
            axes[1].set_xticklabels(x_labels, rotation=45)
            axes[1].set_xlabel('Доза')

            axes[2].bar(x_pos, results['S_norm'], color='red', alpha=0.8)
            axes[2].set_title('S_g Безопасность (риск)', fontweight='bold')
            axes[2].set_xticks(x_pos)
            axes[2].set_xticklabels(x_labels, rotation=45)
            axes[2].set_xlabel('Доза')

            plt.tight_layout()
            st.pyplot(fig)
            plt.close(fig)

            # Интегральный график
            fig2, ax2 = plt.subplots(figsize=(10, 5))
            colors = ['green' if v == results['I_g'].max() else 'steelblue' for v in results['I_g']]
            ax2.bar(x_pos, results['I_g'], color=colors, alpha=0.8)
            ax2.axhline(y=0, color='gray', linestyle='--', alpha=0.5)
            ax2.set_title('I_g Интегральный индекс', fontweight='bold', fontsize=14)
            ax2.set_xticks(x_pos)
            ax2.set_xticklabels(x_labels, rotation=45)
            ax2.set_xlabel('Доза')
            ax2.set_ylabel('I_g')
            plt.tight_layout()
            st.pyplot(fig2)
            plt.close(fig2)

            # Победитель
            best_idx = results['I_g'].idxmax()
            best_dose = results.loc[best_idx, 'Доза']
            best_ig = results.loc[best_idx, 'I_g']

            st.success(f"🎉 **ОПТИМАЛЬНАЯ ДОЗА: {best_dose:.2f}** (I_g = {best_ig:.3f})")

            # Детали лучшей дозы
            col1, col2, col3, col4 = st.columns(4)
            col1.metric("Доза", f"{best_dose:.2f}")
            col2.metric("E (эффективность)", f"{results.loc[best_idx, 'E_norm']:.3f}")
            col3.metric("B (баланс)", f"{results.loc[best_idx, 'B_norm']:.3f}")
            col4.metric("S (риск)", f"{results.loc[best_idx, 'S_norm']:.3f}")

else:
    st.info("📁 Загрузите CSV/Excel файл в боковой панели")
    st.markdown("""
    ### 🚀 Быстрый старт:
    1. **Загрузите** данные эксперимента
    2. **Выберите тип** (крысы/карпы)
    3. **Укажите столбец с дозами** (0 = контроль)
    4. **Выберите признаки**
    5. **Получите** автоматическое ранжирование!
    """)

st.markdown("---")
st.markdown("*© 2026 DoseRanker Pro | Математическая модель*")
